2023-10-27 01:52:19,978 INFO    MainThread:62980 [wandb_setup.py:_flush():76] Current SDK version is 0.15.12
2023-10-27 01:52:19,979 INFO    MainThread:62980 [wandb_setup.py:_flush():76] Configure stats pid to 62980
2023-10-27 01:52:19,979 INFO    MainThread:62980 [wandb_setup.py:_flush():76] Loading settings from C:\Users\COMPUTOCKS\.config\wandb\settings
2023-10-27 01:52:19,979 INFO    MainThread:62980 [wandb_setup.py:_flush():76] Loading settings from c:\Users\COMPUTOCKS\Desktop\semestre_5\machine_learning\wandb\settings
2023-10-27 01:52:19,979 INFO    MainThread:62980 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-10-27 01:52:19,979 INFO    MainThread:62980 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-27 01:52:19,980 INFO    MainThread:62980 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-10-27 01:52:19,980 INFO    MainThread:62980 [wandb_init.py:_log_setup():528] Logging user logs to c:\Users\COMPUTOCKS\Desktop\semestre_5\machine_learning\wandb\run-20231027_015219-c57ex3y9\logs\debug.log
2023-10-27 01:52:19,981 INFO    MainThread:62980 [wandb_init.py:_log_setup():529] Logging internal logs to c:\Users\COMPUTOCKS\Desktop\semestre_5\machine_learning\wandb\run-20231027_015219-c57ex3y9\logs\debug-internal.log
2023-10-27 01:52:19,981 INFO    MainThread:62980 [wandb_init.py:init():568] calling init triggers
2023-10-27 01:52:19,981 INFO    MainThread:62980 [wandb_init.py:init():576] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.02, 'architecture': 'CNN', 'dataset': 'CIFAR-100', 'epochs': 10}
2023-10-27 01:52:19,981 INFO    MainThread:62980 [wandb_init.py:init():594] re-initializing run, found existing run on stack: 75lqbm6m
2023-10-27 01:52:19,983 INFO    MainThread:62980 [wandb_run.py:_finish():1934] finishing run simios/my_FeedForwardNeuralNetwork/75lqbm6m
2023-10-27 01:52:19,984 INFO    MainThread:62980 [jupyter.py:save_history():445] not saving jupyter history
2023-10-27 01:52:19,984 INFO    MainThread:62980 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-10-27 01:52:19,984 INFO    MainThread:62980 [wandb_init.py:_jupyter_teardown():456] cleaning up jupyter logic
2023-10-27 01:52:19,984 INFO    MainThread:62980 [wandb_run.py:_atexit_cleanup():2168] got exitcode: 0
2023-10-27 01:52:19,984 INFO    MainThread:62980 [wandb_run.py:_restore():2151] restore
2023-10-27 01:52:19,985 INFO    MainThread:62980 [wandb_run.py:_restore():2157] restore done
2023-10-27 01:52:48,397 INFO    MainThread:62980 [wandb_init.py:init():618] starting backend
2023-10-27 01:52:48,397 INFO    MainThread:62980 [wandb_init.py:init():622] setting up manager
2023-10-27 01:52:48,397 INFO    MainThread:62980 [backend.py:_multiprocessing_setup():107] multiprocessing start_methods=spawn, using: spawn
2023-10-27 01:52:48,397 INFO    MainThread:62980 [wandb_init.py:init():628] backend started and connected
2023-10-27 01:52:48,413 INFO    MainThread:62980 [wandb_run.py:_label_probe_notebook():1276] probe notebook
2023-10-27 01:52:48,413 INFO    MainThread:62980 [wandb_run.py:_label_probe_notebook():1286] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-10-27 01:52:48,413 INFO    MainThread:62980 [wandb_init.py:init():720] updated telemetry
2023-10-27 01:52:48,413 INFO    MainThread:62980 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
